# Generated by Django 3.2.5 on 2021-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('confirmed', models.TextField()),
            ],
            options={
                'db_table': 'confirmed',
            },
        ),
    ]
