# Generated by Django 3.2.9 on 2021-12-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.TextField()),
                ('serious', models.TextField()),
                ('new_hospitalization', models.TextField()),
                ('confirmed', models.TextField()),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'today',
            },
        ),
        migrations.CreateModel(
            name='Week_avg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.TextField()),
                ('serious', models.TextField()),
                ('new_hospitalization', models.TextField()),
                ('confirmed', models.TextField()),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'week',
            },
        ),
    ]
