# Generated by Django 3.2.9 on 2021-12-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwalling', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='week_avg',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
