# Generated by Django 3.2.9 on 2021-12-13 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crwalling', '0006_auto_20211214_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='week_avg',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
