# Generated by Django 3.2.9 on 2021-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwalling', '0007_auto_20211214_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='week_avg',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
